### ISSUE TITLE
Error 0xe0434352 in Event Viewer

### ISSUE THREAD

**Issue by XiaoTDM** [MicaForEveryone/MicaForEveryone#345]
Guys, My PC is not very stable and it sometimes fails with a blue screen. But when last BSoD happens and I reboot the PC, MFE does not work anymore. (Note: I'm not talking about BSoD issue, but MFE's bug.) And two errors were logged in Event Viewer at the same time.
They show that MFE has an error of 0xe0434352 with an error location of 0x0000000000064c3c and that the error module is located .dll KernelBase. I think this has a probability of being a fault of the MFE itself.

`Faulting application name: MicaForEveryone.exe, version: 1.3.1.2, time stamp: 0x63747414
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2134, time stamp:0xc42b59fb
Exception code: 0xe0434352
Fault offset: 0x0000000000064c3c
Faulting process id: 0x0x25EC
Faulting application start time: 0x0x1D9D0FC27311A96
Faulting application path: D:\Apps\Mica For Everyone\MicaForEveryone.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 2e18c98e-e8e5-4e94-8db4-8b1bece3edf5
Faulting package full name: 
Faulting package-relative application ID:`
`Application: MicaForEveryone.exe
CoreCLR Version: 4.700.22.55902
.NET Core Version: 3.1.32
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception: Duplicate rules found: Process(Finder)
   at MicaForEveryone.Core.Services.SettingsService.LoadRulesAsync()
   at MicaForEveryone.Core.Services.SettingsService.InitializeAsync()
   at MicaForEveryone.Services.AppLifeTimeService.InitializeRuleServiceAsync()
   at MicaForEveryone.Program.Main(String[] args)
   at MicaForEveryone.Program.<Main>(String[] args)`
I will try to reinstall Windows to see if the error happens again, but please also analyze if it's an application bug or some runtime error.
(Sorry, I'm using machine translation, there may be some mistakes.)

![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/142332005/22a467db-a12c-4452-9a90-89ec15b8252b)
![image](https://github.com/MicaForEveryone/MicaForEveryone/assets/142332005/40de4b35-a729-4cd5-b4cc-a6a100315dc6)

**Comment by dongle-the-gadget** [comment]
Error is self-explanatory: `Duplicate rules found: Process(Finder)`

**Comment by XiaoTDM** [comment]
So what causes this problem and how do I solve it? X(

**Comment by dongle-the-gadget** [comment]
Change your rule file (default for your case is `%LOCALAPPDATA%\Mica For Everyone\MicaForEveryone.conf`) to remove the conflicting rule.

**Comment by XiaoTDM** [comment]
Thank you so much! :) MFE is now working. It may be that a recent system crash caused the configuration file to become corrupted. And thank you also for taking the time to help me solve the problem (although this is extremely easy to solve. :| )
