### ISSUE TITLE
couldn't lauhch on Build 26020

### ISSUE THREAD

**Issue by MuscularPuky** [MicaForEveryone/MicaForEveryone#397]
[ ] This is not about other apps being displayed weird or etc.
[ ] This is not about rendering issues that caused by a bug in the Windows.
[ ] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[ ] I've checked other issues and this is not a duplicate.

**Describe the bug**
Application: MicaForEveryone.exe
CoreCLR Version: 4.700.22.55902
.NET Core Version: 3.1.32
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception: Duplicate rules found: Process(PowerToys.PowerLauncher)
   at MicaForEveryone.Core.Services.SettingsService.LoadRulesAsync()
   at MicaForEveryone.Core.Services.SettingsService.InitializeAsync()
   at MicaForEveryone.Services.AppLifeTimeService.InitializeRuleServiceAsync()
   at MicaForEveryone.Program.Main(String[] args)
   at MicaForEveryone.Program.<Main>(String[] args)

오류 있는 응용 프로그램 이름: MicaForEveryone.exe, 버전: 1.3.1.2, 타임스탬프로: 0x63747414
오류 있는 모듈 이름: KERNELBASE.dll, 버전: 10.0.26020.1000, 타임스탬프: 0xbb9fb293
예외 코드: 0xe0434352
오류 오프셋: 0x000000000009d1ca
오류 처리 ID: 0x2FCC
오류 응용 프로그램 시작 시간: 0x1DA441116958FB0
Faulting 응용 프로그램 경로: C:\Program Files\WindowsApps\MicaForEveryone_1.3.1.2_x64__pfhyqtmn5ksmy\MicaForEveryone\MicaForEveryone.exe
Faulting 모듈 경로: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: ef7a30ae-a3f0-4661-bb54-fab92a331983
Faulting 패키지 전체 이름: MicaForEveryone_1.3.1.2_x64__pfhyqtmn5ksmy
Faulting 패키지 상대 응용 프로그램 ID:  MicaForEveryone

**To Reproduce**
couldn't launch mfe by any methods

**Expected behavior**
launched well

**Screenshots**

**Windows Version**
Windows vNext, NT 10.0.26020.1000

**Additional context**

**Comment by MuscularPuky** [comment]
It was config bug. If config contains same class/process line, MFE crashes. MFE filters 2 rules are conflicting but this caises by editing config file with notepad directly
