### ISSUE TITLE
Cant open micaforeveryone using the .exe

### ISSUE THREAD

**Issue by ReLyf47** [MicaForEveryone/MicaForEveryone#437]
[ ] This is not about other apps being displayed weird or etc.
[ ] This is not about rendering issues that caused by a bug in the Windows.
[ ] I've read [FAQ](https://github.com/MicaForEveryone/MicaForEveryone/wiki/FAQ).
[ ] I've checked other issues and this is not a duplicate.

**Describe the bug**
I simply cannot open the settings page using the .exe

**To Reproduce**
1. Open the exe
2. Profit

**Expected behavior**
Opens the settings menu

**Windows Version**
Windows 11 Pro 23H2 22631.3737

**Comment by Sakyce** [comment]
I get this issue too! By looking at Events Observer (or whatever it's called in english), I see this exception:

```
Application: MicaForEveryone.exe
CoreCLR Version: 4.700.22.55902
.NET Core Version: 3.1.32
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Le module spécifié est introuvable. (0x8007007E)
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication..ctor()
   at MicaForEveryone.UI.App..ctor()
   at MicaForEveryone.App..ctor()
   at MicaForEveryone.Services.AppLifeTimeService.<RunViewServiceAsync>b__14_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by 333HaI** [comment]
Im also getting this bug. Has anyone found a solution yet?
